# Required metadata
sonar.projectKey=sygalin-base-python
sonar.projectName=Sygalin Base Python
sonar.projectVersion=1.0

# Path to source code
sonar.sources=.

# Optional: language, exclusions
# sonar.language=python
# sonar.exclusions=**/test/**

# SonarQube server
sonar.host.url=${{ secrets.SONAR_URL }}
sonar.login=${{ secrets.SONAR_TOKEN }}
sonar.python.coverage.reportPaths=coverage.xml
